create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  owner_name text not null,
  owner_phone text not null,
  owner_email text not null,
  pet_name text not null,
  pet_type text not null,
  service_id text not null,
  appointment_date date not null,
  appointment_time time not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists appointments_date_idx on public.appointments (appointment_date);
create index if not exists appointments_status_idx on public.appointments (status);
